# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-11 07:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('img_anuncio', models.ImageField(upload_to='uploads/anuncio/')),
                ('url_anuncio', models.CharField(max_length=255)),
                ('fecha_caducidad', models.DateField()),
                ('estado', models.CharField(max_length=10)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=100)),
                ('img_area', models.ImageField(upload_to='uploads/areas/')),
                ('estado', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AreaInteres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Area')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContenidoCompartido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compartido', models.DateTimeField(auto_now_add=True)),
                ('red_social', models.CharField(choices=[('tw', 'Twitter'), ('wa', 'Whatsapp'), ('fb', 'Facebook')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('pensum', models.FileField(upload_to='uploads/pensums/')),
                ('duracion_cant', models.IntegerField()),
                ('duracion_tipo', models.CharField(choices=[('S', 'Semanas'), ('H', 'Horas')], max_length=1)),
                ('costo', models.FloatField()),
                ('img_curso', models.ImageField(upload_to='uploads/imagenes/')),
                ('estado', models.CharField(max_length=10)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('area_estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Area')),
            ],
        ),
        migrations.CreateModel(
            name='CursoProfesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Frase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('img_frase', models.ImageField(upload_to='uploads/frase/')),
                ('estado', models.CharField(max_length=10)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoalsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=10)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('curso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Curso')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('Mi', 'Miercoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sabado')], max_length=2)),
                ('hora_inicio', models.IntegerField()),
                ('minutos_inicio', models.IntegerField()),
                ('hora_fin', models.IntegerField()),
                ('minutos_fin', models.IntegerField()),
                ('curso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_limite', models.DateField()),
                ('notificacion', models.BooleanField()),
                ('fecha_notificacion', models.DateTimeField()),
                ('estado', models.CharField(max_length=10)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=16)),
                ('apellido', models.CharField(max_length=16)),
                ('titulo', models.CharField(max_length=20)),
                ('img_perfil', models.ImageField(upload_to='uploads/fotoProfesores/')),
                ('frases_personal', models.CharField(max_length=100)),
                ('biografia', models.CharField(max_length=255)),
                ('url_linkedin', models.CharField(max_length=255)),
                ('curriculum', models.FileField(upload_to='uploads/pensums/')),
                ('estado', models.CharField(max_length=10)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('area_especializacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Area')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroUsuarioCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('curso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Curso')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Telefonos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefonos', models.CharField(max_length=12)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('cliente', 'cliente'), ('admin', 'administrador'), ('bloqueado', 'UsuarioBloqueado')], max_length=10)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cursoprofesor',
            name='profesor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Profesor'),
        ),
        migrations.AddField(
            model_name='contenidocompartido',
            name='curso_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Curso'),
        ),
        migrations.AddField(
            model_name='contenidocompartido',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
