# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-30 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180729_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='duracion_tipo',
            field=models.CharField(choices=[('S', 'Semanas'), ('M', 'Meses')], max_length=1),
        ),
    ]
