# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-05 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180730_0141'),
        ('api', '0003_auto_20180729_2237'),
    ]

    operations = [
    ]
